CREATE DATABASE Devbook;
USE Devbook;

CREATE TABLE Users (
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Nick VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(20) NOT NULL UNIQUE,
    CreateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)