CREATE DATABASE Devbook;

CREATE TABLE IF NOT EXISTS Users (
 Id SERIAL,
 Name VARCHAR(50) NOT NULL UNIQUE,
 Nick VARCHAR(50) NOT NULL UNIQUE,
 Email VARCHAR(50) NOT NULL UNIQUE,
 Password VARCHAR(20) NOT NULL UNIQUE,
 CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);